### ISSUE TITLE
Using the action on Ubuntu 20.04

### ISSUE THREAD

**Issue by ktbarrett** [ghdl/setup-ghdl-ci#7]
I am using this action on a `ubuntu-20.04` instance with an mcode backend. However I am seeing [an error](https://github.com/ktbarrett/cocotb/pull/4/checks?check_run_id=1193649685) when it tries to install `libllvm5.0`. This package is [no longer available on Ubuntu 20.04](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libllvm5.0&searchon=names).

Since I am using the mcode backend, libllvm does not need to be installed. It might also be a good idea to make it explicit that the llvm backend is not supported on Ubuntu 20.04. Or perhaps there is some easy way to get older llvm versions in 20.04 via PPA?

**Comment by umarcor** [comment]
You are correct. If `mcode` backend is selected, it should not try to install LLVM, regardless of the package existing or not. I will check it.

On the other hand, I didn't know that Ubuntu 20.04 was supported in GitHub Actions. I assumed that `ubuntu-latest` would be, as the name implies, automatically updated. But someone decided to make it fun to maintain: https://github.com/actions/virtual-environments#available-environments. I will add support for 20.04.

**Comment by umarcor** [comment]
Both issues should be fixed now. See: https://github.com/ghdl/setup-ghdl-ci/actions/runs/286862594

**Comment by ktbarrett** [comment]
Thank you @umarcor. Is there a new release in this repo coming? There is a "nightly" release, but I don't see an action where it is built and pushlished (not that it really needs one right now). Also, I think the README needs updating.

**Comment by umarcor** [comment]
My bad 😊 . The nightly tag and the README are updated now.

**Comment by ktbarrett** [comment]
I have confirmed it works, thanks so much!

I'm sure you know, but I also confirmed that `latest` is an alias for a particular version, so `windows-2019` and `ubuntu-latest` are also already-supported OSes.

**Comment by umarcor** [comment]
I added those to the README and to CI (including windows-2016, which is also supported).

BTW, for testing cocotb and/or VUnit, you might want to follow the following approach: https://github.com/umarcor/vunit-cocotb/blob/master/.github/workflows/test.yml. That's for GNU/Linux only, tho, since Windows containers are not supported.
